# Generated by Django 5.2.17 on 2026-10-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_links_as_a', to='genealogy.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_links_as_b', to='genealogy.person')),
            ],
            options={
                'ordering': ['person_a_id', 'person_b_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('person_a', models.F('person_b')), _negated=True), name='sibling_people_differ')],
            },
        ),
    ]
